Repository scalableminds/webknossos-libs, pull requests merged in 2021-11, with the labels that each got.

#470 Add User client
  docs/mkdocs.yml
  docs/src/webknossos-py/examples/learned_segmenter.md
  docs/src/webknossos-py/examples/skeleton_synapse_candidates.md
  docs/src/webknossos-py/examples/upload_image_data.md
  docs/src/webknossos-py/examples/user_times.md
  webknossos/Changelog.md
  webknossos/__generate_client.py
  webknossos/examples/user_times.py
  webknossos/poetry.lock
  webknossos/pyproject.toml
  webknossos/tests/cassettes/test_examples/test_upload_data.yaml
  webknossos/tests/cassettes/test_examples/test_user_times.yaml
  webknossos/tests/cassettes/test_generated_client/test_current_user_info_and_user_logged_time.yaml
  webknossos/tests/cassettes/test_generated_client/test_generate_token_for_data_store.yaml
  webknossos/tests/cassettes/test_generated_client/test_user_list.yaml
  webknossos/tests/client/cassettes/test_context/test_user_organization.yaml
  webknossos/tests/client/cassettes/test_user/test_get_all_managed_users.yaml
  webknossos/tests/client/cassettes/test_user/test_get_current_user.yaml
  webknossos/tests/client/cassettes/test_user/test_get_logged_time.yaml
  webknossos/tests/client/test_context.py
  webknossos/tests/client/test_user.py
  webknossos/tests/test_examples.py
  webknossos/tests/test_generated_client.py
  webknossos/webknossos/client/__init__.py
  webknossos/webknossos/client/_generated/api/datastore/dataset_download.py
  webknossos/webknossos/client/_generated/api/default/current_user_info.py
  webknossos/webknossos/client/_generated/api/default/generate_token_for_data_store.py
  webknossos/webknossos/client/_generated/api/default/user_list.py
  webknossos/webknossos/client/_generated/api/default/user_logged_time.py
  webknossos/webknossos/client/_generated/models/__init__.py
  webknossos/webknossos/client/_generated/models/current_user_info_response_200.py
  webknossos/webknossos/client/_generated/models/current_user_info_response_200_experiences.py
  webknossos/webknossos/client/_generated/models/current_user_info_response_200_novel_user_experience_infos.py
  webknossos/webknossos/client/_generated/models/current_user_info_response_200_teams_item.py
  webknossos/webknossos/client/_generated/models/generate_token_for_data_store_response_200.py
  webknossos/webknossos/client/_generated/models/user_list_response_200_item.py
  webknossos/webknossos/client/_generated/models/user_list_response_200_item_experiences.py
  webknossos/webknossos/client/_generated/models/user_list_response_200_item_novel_user_experience_infos.py
  webknossos/webknossos/client/_generated/models/user_list_response_200_item_teams_item.py
  webknossos/webknossos/client/_generated/models/user_logged_time_response_200.py
  webknossos/webknossos/client/_generated/models/user_logged_time_response_200_logged_time_item.py
  webknossos/webknossos/client/_generated/models/user_logged_time_response_200_logged_time_item_payment_interval.py
  webknossos/webknossos/client/context.py
  webknossos/webknossos/client/user.py
Labels: automerge, hacktoberfest-accepted

#474 Update changelogs
  webknossos/Changelog.md
  wkcuber/Changelog.md
Labels: automerge

#481 skeleton.Graph inheriting from nx.Graph
  webknossos/Changelog.md
  webknossos/tests/test_skeleton.py
  webknossos/webknossos/skeleton/graph.py
  webknossos/webknossos/skeleton/group.py
  webknossos/webknossos/skeleton/nml/from_skeleton.py
  webknossos/webknossos/skeleton/node.py
  webknossos/webknossos/skeleton/skeleton.py
Labels: automerge

#485 Add websites metadata to pyproject.toml
  webknossos/pyproject.toml
Labels: documentation

#493 Update changelogs for release v0.8.23
  webknossos/Changelog.md
  wkcuber/Changelog.md
Labels: automerge
