Repository scalableminds/webknossos-libs, pull requests merged in 2021-07, with the labels that each got.

#339 Small improvements of the dataset API
  Changelog.md
  tests/test_dataset.py
  tests/test_downsampling.py
  tests/test_upsampling.py
  wkcuber/api/__init__.py
  wkcuber/api/dataset.py
  wkcuber/api/layer.py
  wkcuber/api/properties/dataset_properties.py
  wkcuber/compress.py
  wkcuber/mag.py
Labels: automerge

#360 Add optional make_relative: bool to add_symlink_layer
  Changelog.md
  wkcuber/api/dataset.py
Labels: enhancement

#365 Fix add_symlink_layer properties lookup
  Changelog.md
  wkcuber/api/dataset.py
Labels: bug
