Repository scalableminds/webknossos-libs, pull requests merged in 2022-04, with the labels that each got.

#689 add BMP
  wkcuber/Changelog.md
  wkcuber/README.md
  wkcuber/wkcuber/image_readers.py
Labels: automerge

#691 Add documentation to LayerViewConfiguration
  webknossos/webknossos/dataset/properties.py
Labels: documentation

#700 fix traps in test scripts
  _tooling/local_minio_setup.sh
  webknossos/local_wk_setup.sh
  webknossos/test.sh
  webknossos/tests/test_dataset.py
  wkcuber/test.sh
  wkcuber/tests/test_cli.py
Labels: automerge

#697 Allow newer numpy versions
  wkcuber/poetry.lock
  wkcuber/pyproject.toml
  wkcuber/tests/test_metadata.py
  wkcuber/wkcuber/convert_nifti.py
  wkcuber/wkcuber/convert_raw.py
Labels: automerge

#699 docs: add webknossos terminology
  docs/mkdocs.yml
Labels: automerge

#708 typo in assert message
  webknossos/webknossos/annotation/annotation.py
Labels: automerge

#707 typo in doc
  webknossos/webknossos/annotation/annotation.py
Labels: documentation, automerge
