Repository scalableminds/webknossos-libs, pull requests merged in 2022-03, with the labels that each got.

#616 CI: don't run everything twice in PRs
  .github/workflows/ci.yml
Labels: automerge

#637 upgrades kubernetes
  cluster_tools/poetry.lock
  cluster_tools/pyproject.toml
  docs/poetry.lock
  webknossos/poetry.lock
  wkcuber/poetry.lock
Labels: automerge

#644 Use annotation-provided scale for temp volume annotation
  webknossos/Changelog.md
  webknossos/webknossos/annotation/annotation.py
Labels: automerge

#641 Persist log file
  .gitignore
  webknossos/webknossos/utils.py
  wkcuber/.gitignore
  wkcuber/Changelog.md
Labels: wkcuber

#627 ZarrStorageArray and refactorings
  webknossos/Changelog.md
  webknossos/examples/dataset_usage.py
  webknossos/poetry.lock
  webknossos/pyproject.toml
  webknossos/script_collection/globalize_floodfill.py
  webknossos/testdata/complex_property_ds/datasource-properties.json
  webknossos/testdata/old_wkw_dataset/color/1/header.wkw
  webknossos/testdata/old_wkw_dataset/color/2/header.wkw
  webknossos/testdata/old_wkw_dataset/datasource-properties.json
  webknossos/testdata/simple_wkw_dataset/color/1/header.wkw
  webknossos/testdata/simple_wkw_dataset/color/1/z0/y0/x0.wkw
  webknossos/testdata/simple_wkw_dataset/datasource-properties.json
  webknossos/testdata/simple_zarr_dataset/color/1/.zarray
  webknossos/testdata/simple_zarr_dataset/color/1/0.0.0.0
  webknossos/testdata/simple_zarr_dataset/datasource-properties.json
  webknossos/tests/test_dataset.py
  webknossos/tests/test_dataset_deprecated.py
  webknossos/webknossos/annotation/annotation.py
  webknossos/webknossos/client/_download_dataset.py
  webknossos/webknossos/client/_resumable/file.py
  webknossos/webknossos/client/download_dataset.py
  webknossos/webknossos/dataset/__init__.py
  webknossos/webknossos/dataset/_array.py
  webknossos/webknossos/dataset/_utils/buffered_slice_reader.py
  webknossos/webknossos/dataset/_utils/buffered_slice_writer.py
  webknossos/webknossos/dataset/_utils/infer_bounding_box_existing_files.py
  webknossos/webknossos/dataset/compress_utils.py
  webknossos/webknossos/dataset/dataset.py
  webknossos/webknossos/dataset/defaults.py
  webknossos/webknossos/dataset/downsampling_utils.py
  webknossos/webknossos/dataset/layer.py
  webknossos/webknossos/dataset/mag_view.py
  webknossos/webknossos/dataset/properties.py
  webknossos/webknossos/dataset/upsampling_utils.py
  webknossos/webknossos/dataset/view.py
  webknossos/webknossos/geometry/bounding_box.py
  webknossos/webknossos/geometry/vec3_int.py
  webknossos/webknossos/skeleton/__init__.py
  webknossos/webknossos/skeleton/skeleton.py
  webknossos/webknossos/utils.py
  wkcuber/tests/conftest.py
  wkcuber/tests/scripts/all_tests.sh
  wkcuber/tests/test_auto_detection.py
  wkcuber/tests/test_downsampling.py
  wkcuber/tests/test_export_wkw_as_nifti.py
  wkcuber/tests/test_upsampling.py
  wkcuber/tests/test_utils.py
  wkcuber/wkcuber/compress.py
  wkcuber/wkcuber/convert_nifti.py
  wkcuber/wkcuber/converter.py
  wkcuber/wkcuber/downsampling.py
  wkcuber/wkcuber/export_wkw_as_tiff.py
  wkcuber/wkcuber/image_readers.py
  wkcuber/wkcuber/knossos.py
  wkcuber/wkcuber/metadata.py
  wkcuber/wkcuber/upsampling.py
  wkcuber/wkcuber/utils.py
Labels: automerge

#658 fix changelog entries
  webknossos/Changelog.md
Labels: automerge

#657 Fix downsampling/compression of segmentation layers + misc
  .github/workflows/ci.yml
  webknossos/Changelog.md
  webknossos/webknossos/dataset/layer.py
  webknossos/webknossos/dataset/mag_view.py
  webknossos/webknossos/utils.py
  wkcuber/format.sh
  wkcuber/lint.sh
  wkcuber/poetry.lock
  wkcuber/pyproject.toml
  wkcuber/tests/test_main.py
  wkcuber/tests/test_raw_conversion.py
  wkcuber/typecheck.sh
  wkcuber/wkcuber/converter.py
  wkcuber/wkcuber/cubing.py
Labels: automerge

#643 enable anisotropic nearest interpolation downsampling
  webknossos/webknossos/dataset/downsampling_utils.py
  webknossos/webknossos/dataset/layer.py
  wkcuber/Changelog.md
  wkcuber/wkcuber/downsampling.py
  wkcuber/wkcuber/utils.py
Labels: wkcuber

#639 organization_id to organization_name
  webknossos/Changelog.md
  webknossos/__generate_client.py
  webknossos/examples/apply_merger_mode.py
  webknossos/examples/download_image_data.py
  webknossos/examples/learned_segmenter.py
  webknossos/tests/client/test_context.py
  webknossos/webknossos/administration/user.py
  webknossos/webknossos/client/_download_dataset.py
  webknossos/webknossos/client/_generated/models/__init__.py
  webknossos/webknossos/client/_generated/models/dataset_info_response_200_data_source.py
  webknossos/webknossos/client/_generated/models/dataset_info_response_200_data_source_data_layers_item.py
  webknossos/webknossos/client/_generated/models/dataset_info_response_200_data_source_data_layers_item_default_view_configuration.py
  webknossos/webknossos/client/_upload_dataset.py
  webknossos/webknossos/client/context.py
  webknossos/webknossos/dataset/dataset.py
Labels: v2

#667 fixes compression of downsampled mags
  webknossos/Changelog.md
  webknossos/tests/test_dataset.py
  webknossos/webknossos/dataset/mag_view.py
Labels: automerge

#649 Cloud storage support for wklibs+zarr
  cluster_tools/cluster_tools/__init__.py
  docs/poetry.lock
  webknossos/.gitignore
  webknossos/Changelog.md
  webknossos/poetry.lock
  webknossos/pyproject.toml
  webknossos/stubs/upath/__init__.py
  webknossos/test.sh
  webknossos/tests/client/test_context.py
  webknossos/tests/client/test_user.py
  webknossos/tests/test_annotation.py
  webknossos/tests/test_dataset.py
  webknossos/tests/test_dataset_download_upload.py
  webknossos/tests/test_examples.py
  webknossos/tests/test_generated_client.py
  webknossos/webknossos/dataset/_array.py
  webknossos/webknossos/dataset/dataset.py
  webknossos/webknossos/dataset/layer.py
  webknossos/webknossos/dataset/mag_view.py
  webknossos/webknossos/utils.py
  wkcuber/poetry.lock
  wkcuber/test.sh
  wkcuber/wkcuber/compress.py
Labels: automerge
