Repository scalableminds/webknossos-libs, pull requests merged in 2024-11, with the labels that each got.

#1214 Add GA workflow to verify the wk package installation
  .github/workflows/verify_published.yml
Labels: CI

#1219 Fix install "all extras" for Python 3.12
  docs/src/webknossos-py/installation.md
  webknossos/Changelog.md
  webknossos/README.md
  webknossos/pyproject.toml
  webknossos/webknossos/dataset/_utils/pims_czi_reader.py
  webknossos/webknossos/dataset/dataset.py
Labels: bug

#1220 Fix "verify published" CI workflow
  .github/workflows/verify_published.yml
Labels: bug, CI

#1221 Fix ssl context pickling, again
  webknossos/Changelog.md
  webknossos/webknossos/dataset/defaults.py
Labels: automerge
