Repository scalableminds/webknossos-libs, pull requests merged in 2024-09, with the labels that each got.

#1179 [API Documentation] Cover more submodules
  docs/generate_api_doc_pages.py
  docs/mkdocs.yml
Labels: documentation

#1182 Fix nightly tests
  CONTRIBUTING.md
  cluster_tools/README.md
  cluster_tools/dockered-slurm/README.md
  cluster_tools/dockered-slurm/register_cluster.sh
  webknossos/local_wk_setup.sh
Labels: automerge

#1183 format doc strings as Google style
  docs/mkdocs.yml
  docs/src/webknossos-py/examples/dataset_usage.md
  docs/src/webknossos-py/examples/download_image_data.md
  webknossos/webknossos/geometry/bounding_box.py
  webknossos/webknossos/geometry/nd_bounding_box.py
  webknossos/webknossos/geometry/vec_int.py
Labels: documentation

#1189 Add linkchecker config
  .github/workflows/ci.yml
  .github/workflows/publish_docs.yml
  docs/linkcheckerrc
Labels: documentation

#1187 Add option to add remote mags and remote layer to an existing dataset
  webknossos/tests/dataset/cassettes/test_dataset_add_remote_mag_and_layer/test_add_remote_layer_from_object.yaml
  webknossos/tests/dataset/cassettes/test_dataset_add_remote_mag_and_layer/test_add_remote_mags_from_mag_view.yaml
  webknossos/tests/dataset/test_dataset.py
  webknossos/tests/dataset/test_dataset_add_remote_mag_and_layer.py
  webknossos/webknossos/dataset/dataset.py
  webknossos/webknossos/dataset/layer.py
  webknossos/webknossos/dataset/mag_view.py
  webknossos/webknossos/dataset/ome_metadata.py
  webknossos/webknossos/utils.py
Labels: enhancement, wklibs
