Repository scalableminds/webknossos-libs, pull requests merged in 2024-04, with the labels that each got.

#966 Reading nd datasets
  docs/mkdocs.yml
  docs/src/webknossos-py/examples/convert_4d_tiff.md
  webknossos/Changelog.md
  webknossos/examples/convert_4d_tiff.py
  webknossos/testdata/4D/4D_series/4D-series.ome.tif
  webknossos/tests/dataset/test_add_layer_from_images.py
  webknossos/webknossos/_nml/parameters.py
  webknossos/webknossos/annotation/annotation.py
  webknossos/webknossos/cli/convert_knossos.py
  webknossos/webknossos/cli/export_wkw_as_tiff.py
  webknossos/webknossos/dataset/_array.py
  webknossos/webknossos/dataset/_utils/buffered_slice_reader.py
  webknossos/webknossos/dataset/_utils/buffered_slice_writer.py
  webknossos/webknossos/dataset/_utils/infer_bounding_box_existing_files.py
  webknossos/webknossos/dataset/_utils/pims_images.py
  webknossos/webknossos/dataset/dataset.py
  webknossos/webknossos/dataset/layer.py
  webknossos/webknossos/dataset/mag_view.py
  webknossos/webknossos/dataset/properties.py
  webknossos/webknossos/dataset/view.py
  webknossos/webknossos/geometry/__init__.py
  webknossos/webknossos/geometry/bounding_box.py
  webknossos/webknossos/geometry/nd_bounding_box.py
  webknossos/webknossos/geometry/vec3_int.py
  webknossos/webknossos/geometry/vec_int.py
Labels: enhancement

#1024 Reduce default wk-libs dependencies
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  cluster_tools/Changelog.md
  cluster_tools/README.md
  cluster_tools/cluster_tools/executors/dask.py
  cluster_tools/cluster_tools/schedulers/kube.py
  cluster_tools/dockered-slurm/docker-compose.yml
  cluster_tools/poetry.lock
  cluster_tools/pyproject.toml
  cluster_tools/tests/Dockerfile
  docs/src/cli/index.md
  webknossos/Changelog.md
  webknossos/Dockerfile
  webknossos/README.md
  webknossos/poetry.lock
  webknossos/pyproject.toml
  webknossos/webknossos/cli/convert_nifti.py
  webknossos/webknossos/cli/main.py
  wkcuber/README.md
Labels: dependencies

#1046 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
