Repository scalableminds/webknossos-libs, pull requests merged in 2025-04, with the labels that each got.

#1287 Fix upsampling
  webknossos/Changelog.md
  webknossos/tests/dataset/test_upsampling.py
  webknossos/webknossos/dataset/_downsampling_utils.py
  webknossos/webknossos/dataset/_upsampling_utils.py
Labels: automerge

#1283 Add require unique name param to announce manual upload
  webknossos/Changelog.md
  webknossos/webknossos/client/api_client/datastore_api_client.py
  webknossos/webknossos/client/api_client/models.py
  webknossos/webknossos/dataset/dataset.py
Labels: enhancement, wklibs

#1289 Add clarification that bounding box size is in units of voxels
  webknossos/Changelog.md
  webknossos/webknossos/geometry/bounding_box.py
Labels: documentation
