Repository scalableminds/webknossos-libs, pull requests merged in 2025-02, with the labels that each got.

#1252 Update requires python to <3.14
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/publish_docs.yml
  cluster_tools/tests/Dockerfile
  webknossos/Dockerfile
  webknossos/pyproject.toml
  webknossos/uv.lock
Labels: dependencies

#1253 Added "Today I learned" section to docs
  docs/mkdocs.yml
  webknossos/README.md
Labels: documentation

#1254 Add fix for issue in setuptools.
  cluster_tools/pyproject.toml
  webknossos/pyproject.toml
Labels: bug

#1256 Parse dataset id from downloaded nml
  webknossos/Changelog.md
  webknossos/testdata/annotations/l4dense_motta_et_al_demo_v2__explorational__4a6356.zip
  webknossos/tests/test_annotation.py
  webknossos/webknossos/_nml/parameters.py
  webknossos/webknossos/annotation/_nml_conversion.py
Labels: bug, wklibs
