Repository scalableminds/webknossos-libs, pull requests merged in 2025-01, with the labels that each got.

#1233 Make `typing-extensions` a regular dependency
  cluster_tools/pyproject.toml
Labels: dependencies, clustertools

#1235 cluster_tools: In worker, use Python's defaults if `logging_config` is missing
  cluster_tools/cluster_tools/remote.py
Labels: clustertools

#1234 correct NDBoundingBox docstring example
  webknossos/webknossos/geometry/nd_bounding_box.py
Labels: documentation

#1249 Update Python metadata to include py3.13
  webknossos/pyproject.toml
Labels: documentation
